version: "3.9"
services:
  vertica-ce:
    image: 957650740525.dkr.ecr.ap-south-1.amazonaws.com/vertica-ce:v1.0
    container_name: vertica-ce
    ports:
      - "5433:5433"
    restart: unless-stopped
    volumes:
      - ./_data/vertica:/data
  mcp-vertica:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: mcp-vertica
    environment:
      VERTICA_HOST: vertica-ce
      VERTICA_PORT: "5433"
      VERTICA_DATABASE: VMart
      VERTICA_USER: dbadmin
      VERTICA_PASSWORD: ""
      VERTICA_CONNECTION_LIMIT: "5"
      MCP_MAX_CONCURRENT_QUERIES: "4"
      # MCP_HTTP_TOKEN: "set-me-for-remote"
      # ALLOWED_ORIGINS: "https://smithery.ai,https://app.anthropic.com"
    ports:
      - "8000:8000"
    depends_on:
      - vertica-ce
    restart: unless-stopped
volumes:
  vertica:
    driver: local
