services:
  vertica:
    image: ${VERTICA_IMAGE_URI}
    ports:
      - "5433:5433"
  mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    environment:
      VERTICA_HOST: vertica
      VERTICA_PORT: "5433"
      VERTICA_USER: ${VERTICA_USER}
      VERTICA_PASSWORD: ${VERTICA_PASSWORD}
      VERTICA_DATABASE: ${VERTICA_DATABASE}
      MCP_HTTP_TOKEN: ${MCP_HTTP_TOKEN}
    ports:
      - "8000:8000"
    depends_on:
      - vertica
