services:
  vertica-ce:
    image: ${VERTICA_IMAGE_URI}
    container_name: vertica-ce
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "5433:5433"
    volumes:
      - /var/lib/vertica:/data
  mcp-vertica:
    image: ${MCP_IMAGE_URI}
    container_name: mcp-vertica
    restart: unless-stopped
    environment:
      VERTICA_HOST: 172.17.0.1
      VERTICA_PORT: "5433"
      VERTICA_DATABASE: VMart
      VERTICA_USER: dbadmin
      VERTICA_PASSWORD: ""
      VERTICA_CONNECTION_LIMIT: "5"
      MCP_HTTP_TOKEN: ${MCP_HTTP_TOKEN}
      ALLOWED_ORIGINS: "https://smithery.ai,https://app.anthropic.com"
    ports:
      - "8000:8000"
    depends_on:
      - vertica-ce
